# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0002_auto_20171225_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='link2',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка на медиа 2'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
