# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0003_auto_20171225_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='link2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на медиа 2'),
        ),
    ]
