# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0006_auto_20171225_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='link2',
        ),
        migrations.AddField(
            model_name='lesson',
            name='link2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на медиа 2'),
        ),
    ]
