# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0007_auto_20171225_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Word файл'),
        ),
    ]
