# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0008_auto_20171225_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_active',
        ),
    ]
